### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by NikosDelijohn** [v3l0c1r4pt0r/makeelf#8]
Is there any documentation for your library besides the README ? Can I find it somewhere?

**Comment by v3l0c1r4pt0r** [comment]
There is generated Doxygen, linked on the top of main project page. Here is the link: https://static.re-ws.pl/makeelf/master/ It might come from one of the previous patch releases, but it should still be up-to-date, as in the meantime only bugs were being fixed.

BTW you can always generate it yourself by typing `doxygen` in root of repository.

Do you think anything else should be prepared? I think README covers all of the high-level interfaces and Doxygen describes the details.

**Comment by NikosDelijohn** [comment]
Thank you very much. I didn't notice the Doxygen at your repo. !

**Comment by v3l0c1r4pt0r** [comment]
You're welcome
